"""add coupon scope

Revision ID: d458990079d8
Revises: f2def0638805
Create Date: 2026-05-18 16:53:51.246604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd458990079d8'
down_revision: Union[str, None] = 'f2def0638805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('coupons', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'product_id')
    op.drop_column('coupons', 'scope')
    # ### end Alembic commands ###
